Disable ruby_hl_lvar plugin because of an error
The following error occurs on CentOS 6.6.

    Error detected while processing
    /home/username/.vim/bundle/ruby_hl_lvar.vim/autoload/ruby_hl_lvar.vim:
    line    3:
    LoadError: no such file to load -- ripper